FROM ghcr.io/archlinux/archlinux:base-devel

RUN pacman --noconfirm -Syu --needed \
    ca-certificates ccache cmake git ninja \
    mingw-w64-binutils mingw-w64-crt mingw-w64-gcc \
    mingw-w64-headers mingw-w64-winpthreads